name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22  # Specify your project's Node.js version

    - name: Install dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/ng-otp-input-repo/browser  # Adjust to your build output directory
